# Generated by Django 5.1.3 on 2024-11-30 19:05

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('metadata', models.JSONField(default=dict)),
                ('rating', models.DecimalField(decimal_places=2, max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
            ],
        ),
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('language', models.CharField(max_length=100)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='channel_pictures/')),
                ('parent_channel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subchannels', to='myapp.channel')),
                ('contents', models.ManyToManyField(blank=True, to='myapp.content')),
            ],
        ),
        migrations.CreateModel(
            name='ContentFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='content_files/')),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='myapp.content')),
            ],
        ),
    ]
